app/games/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, HiddenField, TextAreaField, SelectField, IntegerField
from wtforms.validators import DataRequired, ValidationError, Length
from app.models import User, Log, Code, Game
from flask_login import current_user
from app.games import current_game,current_log,current_code


class CreateGameForm(FlaskForm):
	user_id = HiddenField('User id', default=current_user)
	game_name = TextAreaField('game_name', validators=[DataRequired()])
	descript = TextAreaField('descript', validators=[DataRequired()])
	player_num = IntegerField('player_num')
	category_id = IntegerField('category_id')

	game_lib_id = TextAreaField('game_lib_id')#, validators=[DataRequired()]
	example_code = TextAreaField('example code')# , validators=[DataRequired()]
	language = SelectField(
		'Programming Language',
		choices=[('cpp', 'C++'), ('py', 'Python'), ('js', 'Javascript')]
	)
	create = SubmitField('Create Game')
	
class AddRoomForm(FlaskForm):
	roomname = StringField('roomname', validators=[Length(min=0, max=20)])
	game_category = SelectField('Game Category',coerce=int,choices=[])
	game =  SelectField('Game',coerce=int,choices=[])
	user_id = HiddenField('User id', default=current_user)
	privacy =  SelectField('Opponent',coerce=int,choices=[])
	player_num  = IntegerField('player_num')#game.player_num
	
	submit = SubmitField('Enter Gameroom')
	# def validate_roomname(self, roomname):
	# 	room = Log.query.filter_by(roomname=roomname.data).first()
		# if room is not None:
		# 	raise ValidationError('Please use a different roomname.')



class LoginForm(FlaskForm):
	"""Accepts a nickname and a room."""
	name = StringField('UserName', validators=[DataRequired()])
	room = StringField('GameRoomId', validators=[DataRequired()])
	submit = SubmitField('Enter Chatroom')

class JoinForm(FlaskForm):
	submit = SubmitField('Join game')
class LeaveForm(FlaskForm):
	submit = SubmitField('Leave Chatroom')

app/games/__init__.py
from flask import Blueprint

bp = Blueprint('games', __name__)
global current_game, current_log, current_code
current_game=123 
current_log='001'
current_code='010'
from app.games import routes,events

# class current_log(object):
# 	"""docstring for current_log"""
# 	def id():
# 		return '001'
# 	def game_id():
# 		pass
# 	def user_id():
# 		pass

app/games/routes.py
from flask import render_template, flash, redirect, url_for, request, current_app, session
from app import db
from app.games.forms import CreateGameForm, AddRoomForm, LoginForm, JoinForm, LeaveForm
from flask_login import current_user, login_user, logout_user,login_required
from app.models import User, Game, Log, Code,Privacy,News,P_Score
from werkzeug.urls import url_parse
from werkzeug.utils import secure_filename
from datetime import datetime
from app.games import bp
from websocket import create_connection
import json, sys
from .events import * # //in codegame.py

@bp.route('/create_game', methods=['GET', 'POST'])
@login_required
def create_game():
    # 新增遊戲
    form = CreateGameForm()
    if form.validate_on_submit():
        game = Game(user_id=form.user_id.data,game_name=form.game_name.data,descript=form.descript.data, player_num=form.player_num.data,\
        category_id=form.category_id.data)
        db.session.add(game)
        db.session.commit()

        # '''obj_to_json'''
        g_query=Game.query.filter_by(game_name=form.game_name.data).first()
        result=""
        if isinstance(g_query, list):
            result = obj_to_json(g_query)
       
        game_result=json.dumps(result, cls=ComplexEncoder)
        flash('Congratulations, the game is created!')
        return redirect(url_for('games.add_room', gameObj=game_result))

    return render_template('games/create_game.html', title='Register', form=form)

def room_game_list(user_id,cat_id):
    code = Code.query.with_entities(Code.id,Code.game_id,Game.game_name,Game.descript,Category.name).filter(Code.user_id==user_id,Game.category_id==cat_id).join(Game,(Game.id==Code.game_id)).group_by(Game.id).all()
    game_choices=[(0,"default")]
    game_choices.extend([(g.game_id,g.game_name) for g in code])
    return game_choices

@bp.route('/get_g_list', methods=['GET','POST'])
@login_required
def get_g_list():
    if request.method == 'POST':
        if "text/plain" in request.headers['Content-Type']:
            set_g_option = room_game_list(current_user.id,int(request.data)) 
            # add_form.game.choices=set_g_option   
            return json.dumps({'g_list':set_g_option})

@bp.route('/get_g_player_num', methods=['GET','POST'])
@login_required
def get_g_player_num():
    if request.method == 'POST':
        if "text/plain" in request.headers['Content-Type']:
            game_player_num = Game.query.with_entities(Game.player_num).filter_by(id=int(request.data)).first()
            if len(game_player_num)>0:
                return str(game_player_num[0])
            else:
                return ""
        else:
            print("not \"text/plain\"")
            return ""
    else:
        print("not \"post\"")
        return ""

@bp.route('/add_room', methods=['GET','POST'])
@login_required
def add_room():
    # 開房間, add log data with game,user
    add_form = AddRoomForm()
    def room_category_list(user_id):  
        result_cat = Code.query.with_entities(Code.id,Code.game_id,Game.category_id,Category.name).filter_by(user_id=user_id).join(Game,(Game.id==Code.game_id)).join(Category,(Category.id==Game.category_id)).group_by(Category.id).all()
        cat_choices=[(0,"default")]
        cat_choices.extend([(c.category_id,c.name) for c in result_cat])
        return cat_choices

    if request.method == 'POST':
        add_form.game.choices=room_game_list(current_user.id,add_form.game_category.data) 
        category_list=room_category_list(current_user.id)
        add_form.game_category.choices=category_list  
        add_form.privacy.choices = Privacy.query.with_entities(Privacy.id,Privacy.privacy_name).all()
        if add_form.validate_on_submit():
            privacy=add_form.privacy.data
            player_num = add_form.player_num.data
            status = 0-player_num
            if privacy == 2: # 1-public, 2-official, 3-invited
                status = 0
            elif privacy == 3:
                invite_players = (add_form.invitelist.data).split(',')
            g = Game.query.filter_by(id=add_form.game.data).first()
            g.count +=1
            log = Log(roomname=add_form.roomname.data,game_id=add_form.game.data,privacy=privacy,status=status)
            db.session.add(log)
            # 若是設定 privacy==friends(指定玩家), log.current_users.append((choose_form.player_list).split(','))
            db.session.commit()
            return redirect(url_for('games.wait_to_play',log_id=log.id))
            # return redirect(url_for('games.room_wait',log_id=log.id))
        
    else:
        add_form.game_category.choices =  room_category_list(current_user.id)
        add_form.game.choices = [("0","default")]
        add_form.privacy.choices =  Privacy.query.with_entities(Privacy.id,Privacy.privacy_name).all()

    return render_template('games/room/add_room.html', title='add_room',form=add_form)


@bp.route('/wait_to_play/<int:log_id>', methods=['GET','POST'])
@login_required
def wait_to_play(log_id):
    session['log_id']=log_id
    # 檢查這個log的game有哪些可用的code, 列出語言, 有才讓 html的btn visable
    log_id = session.get('log_id', '')
    l=Log.query.filter_by(id=log_id).first()
    if l:
        all_codes =Code.query.with_entities(Code.id, Code.commit_msg,Language.language_name).filter_by(game_id=l.game_id, user_id=current_user.id).join(Log,(Log.id==log_id)).join(Language,(Language.id==Code.compile_language_id)).order_by(Code.id.desc()).all()
        all_lan=[]
        have_code=False
        try: 
            if len(all_codes) :
                for e in all_codes:
                    all_lan.append(e[2])
                flash(all_lan,'test')
                have_code=True
            else:
                return redirect(url_for('games.index',msg="you need to upload code from the local app first"))
        except Exception as e:
            print('error:',e)
            return redirect(url_for('games.index',msg="error:"+e))
        finally:
            if have_code:
                l= Log.query.filter_by(id=log_id).first()
                current_users = l.current_users
                if l.privacy is 1: # public,可以
                    rank_list_delself=""
                    if l.status < 0: # room還沒滿,可以進來參賽(新增 player_in_log data, update user的 current_log) # if s is not (0 or 1) :
                        game_start=False
                        if current_user not in current_users:
                            join_log(l,l.privacy)
                    
                    elif l.status is 0 :
                        if current_user not in current_users: 
                            print("sorry room is full, can't join game")
                            return redirect(url_for('games.index',msg="sorry, the room is full, can't join game"))
                        else:
                            game_start=False
                            
                    elif l.status ==1 : # gaming
                        game_start=True

                    else: #l.status ==2
                        return redirect(url_for('games.index',msg="sorry, the game is end"))
                        
                elif l.privacy == 2: # official
                    join_log(l,l.privacy)
                    rank_list=l.get_rank_list()
                    rank_list_delself=[]
                    for each_log in rank_list:
                        if each_log.username!=current_user.username:
                            rank_list_delself.append(each_log)
                    game_start=False
                    if l.status ==1 : # gaming
                        game_start=True
                else: # only invited
                    pass
        return render_template('games/game/spa.html', title='wait_play_commit',log=l,rank_list=rank_list_delself,all_codes=all_codes,game_start=game_start)
    else:
        return redirect(url_for('games.index',msg="The room is deleted"))

@bp.route('/rank_list/<int:log_id>', methods=['GET','POST'])
@login_required
def rank_list(log_id):
    l=Log.query.filter_by(id=log_id).first()
    # p_game = P_Score.query.filter_by(game_id=l.game_id).order.all()
    # p_game
    rank_list = l.get_rank_list()
    return render_template('games/game/rank_list.html', title='rank_list',rank_list=rank_list)

@bp.route('/game_status/<int:game_id>', methods=['GET','POST'])
@login_required
def game_status(game_id):
    g_name = Game.query.filter_by(id=game_id).first().game_name
    a_log = Log.query.filter_by(game_id=game_id).first()
    wait_log = Log.query.filter(Log.status<0,Log.game_id==game_id).all()
    gaming_log = Log.query.filter(Log.status==1,Log.game_id==game_id).all()
    game_players = P_Score.query.join(User,User.id==P_Score.user_id).with_entities(User.username,P_Score.score).order_by(P_Score.score.desc()).all()
    if a_log:
        rank_list = a_log.get_rank_list()
        return render_template('games/game/game_status.html', title='game_status',g_name=g_name,game_players=game_players,wait_log=wait_log,gaming_log=gaming_log,rank_list=rank_list)
    else:
        return redirect(url_for('games.index',msg="The game has no room"))

@bp.route('/display_record/<int:log_id>', methods=['GET','POST'])
@login_required
def display_record(log_id):
    log = Log.query.filter_by(id=log_id).first()
    lan1=Language.query.filter_by(id=log.the_codes[0].compile_language_id).first()
    lan2=Language.query.filter_by(id=log.the_codes[1].compile_language_id).first()
    record_content = json.loads(log.record_content)
    p1=User.query.filter_by(id=record_content['record_content'][0]['P1']).first().username
    p2=User.query.filter_by(id=record_content['record_content'][0]['P2']).first().username
    func_type = request.args.get('func_type')
    
    return render_template('games/game/display.html', title='display',players=[p1,p2],content=record_content['record_content'][1:],func_type=func_type,log_id=log_id,p1_code=log.the_codes[0].body,p2_code=log.the_codes[1].body,p1_lan_mode=lan1.language_name,p2_lan_mode=lan2.language_name)

app/templates/games/game/display.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content %}
<script language="JavaScript" type="text/javascript" src="{{ url_for('static', filename='jquery-3.3.1.js') }}"></script>
<script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
<div class="popup" style="visibility:hidden" >
        <span class="popuptext" id="myPopup">Display end
            <button class="btn ml-4" onclick="download_log()">download</button>
        </span>
    </div>
<div class="container" id="game_playground">

    <h2> game_playground </h2>
    <div class="players">
        <div class="player">
            <div id="map_left_user"> P1 username</div>
        </div>
        <span>vs</span>
        <div class="player">
            <div id="map_right_user"> P2 username</div>
        </div>
    </div>
    <div id="game_display">
        <div class="row" style="height:500px">
    
                <div class =playground>
                <div class="ball"></div>
                <div class = "left-goalkeeper goalkeeper"></div>
                <div class = "right-goalkeeper goalkeeper"></div>
                </div>
        </div>
    </div>
    <div id="p1_code">
            <pre id="editor1" style="height:255px"></pre>
    </div>
    <div id="p2_code">
            <pre id="editor2" style="height:255px"></pre>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.4/ace.js" type="text/javascript" charset="utf-8"></script>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='gameover.css') }}">

<script>
    window.addEventListener('resize', evt => {
    rwd_playground();
});
    let code_decode1 = atob("{{p1_code}}");
    let code_decode2 = atob("{{p2_code}}");
    let editor1 = ace.edit("editor1");    
    editor1.setTheme("ace/theme/twilight");
    editor1.session.setMode("ace/mode/{{p1_lan_mode}}");
    editor1.setValue(code_decode1);
    editor1.setReadOnly(true)
    let editor2 = ace.edit("editor2");    
    editor2.setTheme("ace/theme/twilight");
    editor2.session.setMode("ace/mode/{{p2_lan_mode}}");
    editor2.setValue(code_decode2);
    editor2.setReadOnly(true)

    $('#map_left_user').html({{players | safe }}[0]);
    document.getElementById("map_right_user").textContent={{players | safe }}[1]; 
    let display_content ={{content}}
    let display ={{content}}
    var startTime=new Date();
    var speed=10;
    var start_flag=0;

    function ball_update(relative_pos){
        var width = $(".ball").outerWidth();
        var height = $(".ball").outerHeight();
        // console.log($(".ball").left())
        $(".ball").css({"left":relative_pos[0]+"%" ,"top":relative_pos[1]+"%"});
    }
    function paddle_update(relative_pos,direction){
        direction.css("top",relative_pos+"%");
    }
    function score_update(newscores){
        Scores.setLeft(newscores[0]);
        Scores.setRight(newscores[1]);
    }
    function display_end(){
        var popup = document.getElementById("myPopup");
        popup.classList.toggle("show");
    }
    function download_log(){
        let ball="BALL: ";
        let p1="P1: ";
        let p1_move="P1MOVE: ";
        let p2="P2: ";
        let p2_move="P2MOVE: ";
        for (var i = 0; i < display_content.length; i++) { 
            ball +=  display_content[i][0]+"''";
            p1 +=  display_content[i][1]+"''";
            p1_move +=  display_content[i][2]+"''";
            p2 +=  display_content[i][3]+"''";
            p2_move +=  display_content[i][4]+"''";
        }
        var element = document.createElement('a');
        element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(ball+"\n\n"+p1+"\n\n"+p1_move+"\n\n"+p2+"\n\n"+p2_move));
        element.setAttribute('download', 'log_'+{{log_id}});
        element.style.display = 'none';
        document.body.appendChild(element);
        element.click();
        document.body.removeChild(element);
    }
    function rwd_playground() {
    scaling_ratio=$(".playground").width()/800;
        $(".playground").height(400 * scaling_ratio);
        // 球要在這邊設長寬
        let ball_r=40 * scaling_ratio;
        $(".ball").height(ball_r);
        $(".ball").width(ball_r);
}
    if( {{func_type}} ){ //func_type==1 -> display
        var refreshIntervalId=setInterval(function(){
            position=display.shift();
            if(position == undefined){
                console.log("clearInterval");
                clearInterval(refreshIntervalId);
                display_end();
            }else{ 
            let left = $('.left-goalkeeper')
            let right = $('.right-goalkeeper')
            ratio_ball=[((position[0][0]-20)/8).toFixed(1),((position[0][1]-20)/4).toFixed(1)]
            ratio_paddle1 = ((position[1][1]-66)/4).toFixed(1)
            ratio_paddle2 = ((position[3][1]-66)/4).toFixed(1)
            ball_update(ratio_ball);
            paddle_update(ratio_paddle1,left);
            paddle_update(ratio_paddle2,right);
            }
        },speed);
    }else{
        download_log();
    }
    </script>
    {% endblock %}

app/templates/games/game/game_status.html
<body background="https://i.imgur.com/OPE70hq.jpg">
{% extends "base.html" %}
{% block app_content %}
<br>
<h3 style="color: white;">{{g_name}} status</h3>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='list_css.css') }}">
<div class="flex-container">
    <div class="leaderboard">
        <div class="modal-content">
            <div class="panel-body table-responsive">
                    <table class="table ">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">Rank</th>
                                <th scope="col">Player</th>
                                <th scope="col">Score</th>
                            </tr>
                            </thead>
                            <tbody>
                            <h3>Leaderboard</h3>
                            {% set i=0 %}
                            {% for p_g in game_players %}
                                {% set i=i+1 %}
                                <tr>
                                    <td>{{ loop.index }}</td>
                                    <td><a href="{{ url_for('main.user',username=p_g.username ) }}">{{ p_g.username }}</a></td>
                                    <td>{{ p_g.score }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
            </div>
        </div>
    </div>
    <div class="tables-container">
            <div class="modal-content">
                <div class="panel-body table-responsive">
                    <table class="table ">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">Index</th>
                            <th scope="col">RoomName</th>
                            <th scope="col">Player(s)</th>
                            <th scope="col">Enter</th>
                        </tr>
                        </thead>
                        <tbody>
                        <h4>Waiting Rooms</h4>
                        {% set i=0 %}
                        {% for log in wait_log %}
                            {% set i=i+1 %}
                            <tr>
                                <td>{{ loop.index }}</td>
                                <td>{{ log.roomname }}</td>
                                <td>{{ log.username }}</td>
                                <td><button class="btn btn-info" onclick="javascript:location.href='{{ url_for('games.wait_to_play',log_id=log.id ) }}'" >Enter</button></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="panel-body table-responsive">
                    <table class="table ">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">Rank</th>
                            <th scope="col">RoomName-ID</th>
                            <th scope="col">Ｗinner</th>
                            <th scope="col">Score</th>
                            <th scope="col">Record</th>
                            <th scope="col">Download</th>
                        </tr>
                        </thead>
                        <tbody>
                        <h4>Rank of Rooms</h4>
                        {% set i=0 %}
                        {% for log in rank_list %}
                            {% set i=i+1 %}
                            <tr>
                                <td>{{ loop.index }}</td>
                                <td>{{ log.roomname }}-{{ log.id }}</td>
                                <td>{{ log.username }}</td>
                                <td>{{ log.score }}</td>
                                <td><button class="btn btn-info" onclick="javascript:location.href='{{ url_for('games.display_record',log_id=log.id,func_type=1 ) }}'" >Record</button></td> 
                                <td><button class="btn btn-info" onclick="javascript:location.href='{{ url_for('games.display_record',log_id=log.id,func_type=0 ) }}'" >Download</button></td> 
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="panel-body table-responsive">
                    <table class="table ">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">index</th>
                            <th scope="col">RoomName</th>
                            <th scope="col">UserName</th>
                        </tr>
                        </thead>
                        <tbody>
                        <h4>Gaming Rooms</h4>
                        {% set i=0 %}
                        {% for g_log in gaming_log %}
                            {% set i=i+1 %}
                            <tr>
                                <td>{{ loop.index }}</td>
                                <td>{{ g_log.roomname }}</td>
                                <td>{{ g_log.username }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                
            </div>         
    </div>
</div>

<script>
    function enterRoom(room_id) {
        
        console.log($(room_id));
        var log_id =$(room_id)[0];
        console.log(typeof(log_id));
    }
</script>
{% endblock %}
</body>

app/templates/games/game/rank_list.html
<body background="https://i.imgur.com/OPE70hq.jpg">
{% extends "base.html" %}
{% block app_content %}
<br>
<h3 style="color: antiquewhite">rank_list</h3>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='list_css.css') }}">
<div class="container">
        <div class="modal-content">
            <div class="panel-body table-responsive">
                <table class="table ">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Rank</th>
                        <th scope="col">UserName</th>
                        <th scope="col">Score</th>
                        <th scope="col">LogID</th>
                        <th scope="col">Record</th>
                    </tr>
                    </thead>
                    <tbody>
                    <p>rank_list</p>
                    {% set i=0 %}
                    {% for log in rank_list %}
                        {% set i=i+1 %}
                        <tr>
                            <td>{{ loop.index }}</td>
                            <td>{{ log.username }}</td>
                            <td>{{ log.score }}</td>
                            <td>{{ log.id }}</td>
                            <td><button class="btn btn-info" onclick="javascript:location.href='{{ url_for('games.display_record',log_id=log.id,func_type=1 ) }}'" >Record</button></td> 
                            <td><button class="btn btn-info" onclick="javascript:location.href='{{ url_for('games.display_record',log_id=log.id,func_type=0 ) }}'" >Download</button></td> 
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        
</div>
<script>
    function enterRoom(room_id) {
        
        console.log($(room_id));
        var log_id =$(room_id)[0];
        console.log(typeof(log_id));
    }
</script>
{% endblock %}
</body>