app/games/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, HiddenField, TextAreaField, SelectField, IntegerField
from wtforms.validators import DataRequired, ValidationError, Length
from app.models import User, Log, Code, Game
from flask_login import current_user
from app.games import current_game,current_log,current_code


class CreateGameForm(FlaskForm):
	user_id = HiddenField('User id', default=current_user)
	game_name = TextAreaField('game_name', validators=[DataRequired()])
	descript = TextAreaField('descript', validators=[DataRequired()])
	player_num = IntegerField('player_num')
	category_id = IntegerField('category_id')

	game_lib_id = TextAreaField('game_lib_id')#, validators=[DataRequired()]
	example_code = TextAreaField('example code')# , validators=[DataRequired()]
	language = SelectField(
		'Programming Language',
		choices=[('cpp', 'C++'), ('py', 'Python'), ('js', 'Javascript')]
	)
	create = SubmitField('Create Game')
	
class AddRoomForm(FlaskForm):
	roomname = StringField('roomname', validators=[Length(min=0, max=20)])
	game_category = SelectField('Game Category',coerce=int,choices=[])
	game =  SelectField('Game',coerce=int,choices=[])
	user_id = HiddenField('User id', default=current_user)
	privacy =  SelectField('Opponent',coerce=int,choices=[])
	player_num  = IntegerField('player_num')#game.player_num
	
	submit = SubmitField('Enter Gameroom')
	# def validate_roomname(self, roomname):
	# 	room = Log.query.filter_by(roomname=roomname.data).first()
		# if room is not None:
		# 	raise ValidationError('Please use a different roomname.')



class LoginForm(FlaskForm):
	"""Accepts a nickname and a room."""
	name = StringField('UserName', validators=[DataRequired()])
	room = StringField('GameRoomId', validators=[DataRequired()])
	submit = SubmitField('Enter Chatroom')

class JoinForm(FlaskForm):
	submit = SubmitField('Join game')
class LeaveForm(FlaskForm):
	submit = SubmitField('Leave Chatroom')

app/games/__init__.py
from flask import Blueprint

bp = Blueprint('games', __name__)
global current_game, current_log, current_code
current_game=123 
current_log='001'
current_code='010'
from app.games import routes,events

# class current_log(object):
# 	"""docstring for current_log"""
# 	def id():
# 		return '001'
# 	def game_id():
# 		pass
# 	def user_id():
# 		pass

app/games/routes.py
from flask import render_template, flash, redirect, url_for, request, current_app, session
from app import db
from app.games.forms import CreateGameForm, AddRoomForm, LoginForm, JoinForm, LeaveForm
from flask_login import current_user, login_user, logout_user,login_required
from app.models import User, Game, Log, Code,Privacy,News,P_Score
from werkzeug.urls import url_parse
from werkzeug.utils import secure_filename
from datetime import datetime
from app.games import bp
from websocket import create_connection
import json, sys
from .events import * # //in codegame.py

@bp.route('/create_game', methods=['GET', 'POST'])
@login_required
def create_game():
    # 新增遊戲
    form = CreateGameForm()
    if form.validate_on_submit():
        game = Game(user_id=form.user_id.data,game_name=form.game_name.data,descript=form.descript.data, player_num=form.player_num.data,\
        category_id=form.category_id.data)
        db.session.add(game)
        db.session.commit()

        # '''obj_to_json'''
        g_query=Game.query.filter_by(game_name=form.game_name.data).first()
        result=""
        if isinstance(g_query, list):
            result = obj_to_json(g_query)
       
        game_result=json.dumps(result, cls=ComplexEncoder)
        flash('Congratulations, the game is created!')
        return redirect(url_for('games.add_room', gameObj=game_result))

    return render_template('games/create_game.html', title='Register', form=form)

def room_game_list(user_id,cat_id):
    code = Code.query.with_entities(Code.id,Code.game_id,Game.game_name,Game.descript,Category.name).filter(Code.user_id==user_id,Game.category_id==cat_id).join(Game,(Game.id==Code.game_id)).group_by(Game.id).all()
    game_choices=[(0,"default")]
    game_choices.extend([(g.game_id,g.game_name) for g in code])
    return game_choices

@bp.route('/get_g_list', methods=['GET','POST'])
@login_required
def get_g_list():
    if request.method == 'POST':
        if "text/plain" in request.headers['Content-Type']:
            set_g_option = room_game_list(current_user.id,int(request.data)) 
            # add_form.game.choices=set_g_option   
            return json.dumps({'g_list':set_g_option})

@bp.route('/get_g_player_num', methods=['GET','POST'])
@login_required
def get_g_player_num():
    if request.method == 'POST':
        if "text/plain" in request.headers['Content-Type']:
            game_player_num = Game.query.with_entities(Game.player_num).filter_by(id=int(request.data)).first()
            if len(game_player_num)>0:
                return str(game_player_num[0])
            else:
                return ""
        else:
            print("not \"text/plain\"")
            return ""
    else:
        print("not \"post\"")
        return ""

@bp.route('/add_room', methods=['GET','POST'])
@login_required
def add_room():
    # 開房間, add log data with game,user
    add_form = AddRoomForm()
    def room_category_list(user_id):  
        result_cat = Code.query.with_entities(Code.id,Code.game_id,Game.category_id,Category.name).filter_by(user_id=user_id).join(Game,(Game.id==Code.game_id)).join(Category,(Category.id==Game.category_id)).group_by(Category.id).all()
        cat_choices=[(0,"default")]
        cat_choices.extend([(c.category_id,c.name) for c in result_cat])
        return cat_choices

    if request.method == 'POST':
        add_form.game.choices=room_game_list(current_user.id,add_form.game_category.data) 
        category_list=room_category_list(current_user.id)
        add_form.game_category.choices=category_list  
        add_form.privacy.choices = Privacy.query.with_entities(Privacy.id,Privacy.privacy_name).all()
        if add_form.validate_on_submit():
            privacy=add_form.privacy.data
            player_num = add_form.player_num.data
            status = 0-player_num
            if privacy == 2: # 1-public, 2-official, 3-invited
                status = 0
            elif privacy == 3:
                invite_players = (add_form.invitelist.data).split(',')
            g = Game.query.filter_by(id=add_form.game.data).first()
            g.count +=1
            log = Log(roomname=add_form.roomname.data,game_id=add_form.game.data,privacy=privacy,status=status)
            db.session.add(log)
            # 若是設定 privacy==friends(指定玩家), log.current_users.append((choose_form.player_list).split(','))
            db.session.commit()
            return redirect(url_for('games.wait_to_play',log_id=log.id))
            # return redirect(url_for('games.room_wait',log_id=log.id))
        
    else:
        add_form.game_category.choices =  room_category_list(current_user.id)
        add_form.game.choices = [("0","default")]
        add_form.privacy.choices =  Privacy.query.with_entities(Privacy.id,Privacy.privacy_name).all()

    return render_template('games/room/add_room.html', title='add_room',form=add_form)


@bp.route('/wait_to_play/<int:log_id>', methods=['GET','POST'])
@login_required
def wait_to_play(log_id):
    session['log_id']=log_id
    # 檢查這個log的game有哪些可用的code, 列出語言, 有才讓 html的btn visable
    log_id = session.get('log_id', '')
    l=Log.query.filter_by(id=log_id).first()
    if l:
        all_codes =Code.query.with_entities(Code.id, Code.commit_msg,Language.language_name).filter_by(game_id=l.game_id, user_id=current_user.id).join(Log,(Log.id==log_id)).join(Language,(Language.id==Code.compile_language_id)).order_by(Code.id.desc()).all()
        all_lan=[]
        have_code=False
        try: 
            if len(all_codes) :
                for e in all_codes:
                    all_lan.append(e[2])
                flash(all_lan,'test')
                have_code=True
            else:
                return redirect(url_for('games.index',msg="you need to upload code from the local app first"))
        except Exception as e:
            print('error:',e)
            return redirect(url_for('games.index',msg="error:"+e))
        finally:
            if have_code:
                l= Log.query.filter_by(id=log_id).first()
                current_users = l.current_users
                if l.privacy is 1: # public,可以
                    rank_list_delself=""
                    if l.status < 0: # room還沒滿,可以進來參賽(新增 player_in_log data, update user的 current_log) # if s is not (0 or 1) :
                        game_start=False
                        if current_user not in current_users:
                            join_log(l,l.privacy)
                    
                    elif l.status is 0 :
                        if current_user not in current_users: 
                            print("sorry room is full, can't join game")
                            return redirect(url_for('games.index',msg="sorry, the room is full, can't join game"))
                        else:
                            game_start=False
                            
                    elif l.status ==1 : # gaming
                        game_start=True

                    else: #l.status ==2
                        return redirect(url_for('games.index',msg="sorry, the game is end"))
                        
                elif l.privacy == 2: # official
                    join_log(l,l.privacy)
                    rank_list=l.get_rank_list()
                    rank_list_delself=[]
                    for each_log in rank_list:
                        if each_log.username!=current_user.username:
                            rank_list_delself.append(each_log)
                    game_start=False
                    if l.status ==1 : # gaming
                        game_start=True
                else: # only invited
                    pass
        return render_template('games/game/spa.html', title='wait_play_commit',log=l,rank_list=rank_list_delself,all_codes=all_codes,game_start=game_start)
    else:
        return redirect(url_for('games.index',msg="The room is deleted"))

@bp.route('/rank_list/<int:log_id>', methods=['GET','POST'])
@login_required
def rank_list(log_id):
    l=Log.query.filter_by(id=log_id).first()
    # p_game = P_Score.query.filter_by(game_id=l.game_id).order.all()
    # p_game
    rank_list = l.get_rank_list()
    return render_template('games/game/rank_list.html', title='rank_list',rank_list=rank_list)

@bp.route('/game_status/<int:game_id>', methods=['GET','POST'])
@login_required
def game_status(game_id):
    g_name = Game.query.filter_by(id=game_id).first().game_name
    a_log = Log.query.filter_by(game_id=game_id).first()
    wait_log = Log.query.filter(Log.status<0,Log.game_id==game_id).all()
    gaming_log = Log.query.filter(Log.status==1,Log.game_id==game_id).all()
    game_players = P_Score.query.join(User,User.id==P_Score.user_id).with_entities(User.username,P_Score.score).order_by(P_Score.score.desc()).all()
    if a_log:
        rank_list = a_log.get_rank_list()
        return render_template('games/game/game_status.html', title='game_status',g_name=g_name,game_players=game_players,wait_log=wait_log,gaming_log=gaming_log,rank_list=rank_list)
    else:
        return redirect(url_for('games.index',msg="The game has no room"))

@bp.route('/display_record/<int:log_id>', methods=['GET','POST'])
@login_required
def display_record(log_id):
    log = Log.query.filter_by(id=log_id).first()
    lan1=Language.query.filter_by(id=log.the_codes[0].compile_language_id).first()
    lan2=Language.query.filter_by(id=log.the_codes[1].compile_language_id).first()
    record_content = json.loads(log.record_content)
    p1=User.query.filter_by(id=record_content['record_content'][0]['P1']).first().username
    p2=User.query.filter_by(id=record_content['record_content'][0]['P2']).first().username
    func_type = request.args.get('func_type')
    
    return render_template('games/game/display.html', title='display',players=[p1,p2],content=record_content['record_content'][1:],func_type=func_type,log_id=log_id,p1_code=log.the_codes[0].body,p2_code=log.the_codes[1].body,p1_lan_mode=lan1.language_name,p2_lan_mode=lan2.language_name)

app/templates/games/index/discuss.html
<br>
<h3>Discuss</h3>

app/templates/games/index/hotGame_list.html
<br>
<h3 style="color: antiquewhite">Hot Game</h3>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='list_css.css') }}">
<div class="container">
        <div class="modal-content">
            <div class="panel-body table-responsive">
                <table class="table ">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Hot</th>
                        <th scope="col">Game name</th>
                        <th scope="col">Description</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for hg in h_games %}
                        <tr>
                            <td>{{ moment(hg.timestamp).format('LL') }}</td>
                            <td>{{  hg.count }}</td>
                            <td>{{ hg.game_name }}</td>
                            <td>{{  hg.descript }}</td>
                            <td><button class="btn btn-info" onclick="javascript:location.href='{{ url_for('games.game_status',game_id=hg.id ) }}'" >Enter</button></td>
                            
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        
</div>

app/templates/games/index/index.html
<body background="https://i.imgur.com/OPE70hq.jpg">
{% extends "base.html" %}
{% block app_content %}
    
    

        <title color="white">Enter_Game</title>
        <link rel=stylesheet type=text/css href="{{ url_for('static', filename='index_css.css') }}">

        <div class="tab">
            <button class="tablinks" onclick="openTab(event, 'News')">News</button>
            <button class="tablinks" onclick="openTab(event, 'NewGames')">NewGames</button>
            <button class="tablinks" onclick="openTab(event, 'HotGames')">HotGames</button>
            <button class="tablinks" style="z-index:2" onclick="openTab(event, 'Rooms')">Rooms</button>
        </div>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}
        
        <div id="News" class="tabcontent">
                {% include '/games/index/news.html' %}
        </div>
        <div id="NewGames" class="tabcontent">
                {% include '/games/index/newGame_list.html' %}
                <button class="btn btn-info" onclick="creategame()">create game</button>
                <script>
                 function creategame(name)
                    {
                        window.open("{{ url_for('games.create_game')}}");
                        
                    }
                </script>
        </div>
        <div id="HotGames" class="tabcontent">
                {% include '/games/index/hotGame_list.html' %}
        </div>
        <div id="Rooms" class="tabcontent">
            <button onclick="javascript:location.href='/games/add_room'">add room</button>
            {% if wait_rooms or game_rooms %}
                {% include '/games/index/room_list.html' %}
            {% endif %}
        </div>
      
        <script>
                function openTab(evt, evtName) {
                    var i, tabcontent, tablinks;
                    tabcontent = document.getElementsByClassName("tabcontent");
                    for (i = 0; i < tabcontent.length; i++) {
                        tabcontent[i].style.display = "none";
                    }
                    tablinks = document.getElementsByClassName("tablinks");
                    for (i = 0; i < tablinks.length; i++) {
                        tablinks[i].className = tablinks[i].className.replace(" active", "");
                    }
                    document.getElementById(evtName).style.display = "block";
                    evt.currentTarget.className += " active";
                }
                </script>
{% endblock %}
</body>

app/templates/games/index/newGame_list.html
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='list_css.css') }}">
<div class="container">
        <div class="modal-content">
            <div class="panel-body table-responsive">
                <table class="table ">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Game Name</th>
                        <th scope="col">Description</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for g in games %}
                        <tr>
                            <td>{{ moment(g.timestamp).format('LL') }}</td>
                            <td>{{ g.game_name }}</td>
                            <td>{{  g.descript }}</td>
                            <td><button class="btn btn-info" onclick="javascript:location.href='{{ url_for('games.game_status',game_id=g.id ) }}'" >Enter</button></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        
</div>

app/templates/games/index/news.html
<br>
<h3 style="color: antiquewhite">News</h3>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='list_css.css') }}">
<div class="container">
        <div class="modal-content">
            <div class="panel-body table-responsive">
                <table class="table ">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">News</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for n in news %}
                        <tr>
                            <td>{{ moment(n.timestamp).format('LL') }}</td>
                            <td>{{  n.content }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        
</div>

app/templates/games/index/room_list.html
<br>
<h3 style="color: antiquewhite">room_list</h3>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='list_css.css') }}">
<div class="container">
        <div class="modal-content">
            <div class="panel-body table-responsive">
                <table class="table ">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">RoomID</th>
                        <th scope="col">RoomName</th>
                        <th scope="col">GameName</th>
                        <th scope="col">Players</th>
                        <th scope="col">Current</th>
                        <th scope="col">Maximum</th>
                    </tr>
                    </thead>
                    <tbody>
                    <p>Waiting Rooms</p>
                    {% for w_room in wait_rooms %}
                        {% if  w_room.status < 0 %}
                            <tr>
                                <td>{{ w_room.id }}</td>
                                <td>{{ w_room.roomname }}</td>
                                <td>{{ w_room.game_name }}</td>
                                <td>{% for u in w_users[loop.index-1].current_users %} {{ u.username }} {% endfor %}</td>
                                <td>{{ w_room.player_num  | int  + w_room.status | int  }}</td>
                                <td>{{ w_room.player_num }}</td>
                                <td><button class="btn btn-info" onclick="javascript:location.href='{{ url_for('games.wait_to_play',log_id=w_room.id ) }}'" >Enter</button></td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="panel-body table-responsive">
                <table class="table ">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">RoomID</th>
                        <th scope="col">RoomName</th>
                        <th scope="col">GameName</th>
                        <th scope="col">Players</th>
                        <th scope="col">Maximum</th>
                    </tr>
                    </thead>
                    <tbody>
                    <p>Gaming Rooms</p>
                    {% for g_room in game_rooms %}
                        <tr>
                            <td>{{ g_room.id }}</td>
                            <td>{{ g_room.roomname }}</td>
                            <td>{{ g_room.game_name }}</td>
                            <td>{% for u in g_users[loop.index-1].current_users %} {{ u.username }} {% endfor %}</td>
                            <td>{{ g_room.player_num }}</td>
                            <td><button class="btn btn-info" onclick="javascript:location.href='{{ url_for('games.wait_to_play',log_id=g_room.id ) }}'" >Enter</button></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
</div>
<script>
    function enterRoom(room_id) {
        
        console.log($(room_id));
        var log_id =$(room_id)[0];
        console.log(typeof(log_id));
    }
</script>